#
# Dockerfile - Spacewalk
#
# {{ ansible_managed }}


# 1. Base images
FROM     centos:"{{ centos_real_version }}"
MAINTAINER Jeremie CUADRADO <redbeard28>

# 2. Set the environment variable
ARG HTTP_PROXY=
ARG HTTPS_PROXY=
ENV http_proxy ${HTTP_PROXY}
ENV https_proxy ${HTTPS_PROXY}
WORKDIR "{{ workdir_path }}'

# 3. Add the epel, spacewalk, jpackage repository, supervisord
ADD jpackage.repo /etc/yum.repos.d/jpackage.repo
RUN yum install -y epel-release \
 && yum install -y http://spacewalk.redhat.com/yum/"{{ sp_version }}"/RHEL/"{{ centos_real_version }}"/"{{ centos_arch }}"/spacewalk-repo-"{{ sp_repo_version }}".el"{{ centos_real_version }}".noarch.rpm \
 && yum check-update ; yum upgrade -y \
 && yum install -y spacewalk-setup-postgresql spacewalk-postgresql tomcat-native python-setuptools \
 && yum clean all \
 && easy_install pip && pip install supervisor && pip install --upgrade meld3=="{{ meld3_version }}" && mkdir /etc/supervisord.d \
 && rm -rf /root/.cache


# 4. Install supervisord config
ADD supervisord.conf /etc/supervisord.d/supervisord.conf

# 5. Install spacewalk initial and running scripts
ADD answer.txt   /opt/answer.txt
ADD spacewalk.sh /opt/spacewalk.sh

# 6. Start supervisord
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisord.d/supervisord.conf"]

# System Log
VOLUME /var/log

# PostgreSQL Data
VOLUME /var/lib/pgsql/data

# RPM repository
VOLUME /var/satellite

# Bootstrap directory
VOLUME /var/www/html/pub

# Port
EXPOSE 80 443 5222 68 69
