site_name: Common files for the docs
site_url: http://www.redbeard-consulting.fr
repo_url: https://github.com/redbeard28/docs_commons
site_description: Build documentation on github.com
site_author: Jeremie CUADRADO aka redbeard28

theme: readthedocs
pages:
  - [ 'index.md', 'Home' ]
  - [ 'vault.md', 'Howto', 'Inside Vault file']
  - [ 'vars.md', 'Howto', 'Inside Vars']
  - [ 'defaults.md', 'Howto', 'Inside Defaults file']
  - [ 'dockerfile.md', 'Howto', 'Inside Dockerfile file']
  - [ 'license.md', 'About', 'License' ]
  - [ 'about.md', 'About', 'About' ]